set -s set-clipboard on
set -g @plugin 'catppuccin/tmux'
set -g status-position top
set -g status on
set -g default-terminal "screen-256color"
#set -g prefix C-a
set -g repeat-time 1000
set -g mouse on
#unbind C-b
#bind C-a send-prefix
# split dễ nhớ
bind v split-window -h
bind s split-window -v

# chuyển pane
bind -r i select-pane -U   # lên
bind -r k select-pane -D   # xuống
bind -r j select-pane -L   # trái
bind -r l select-pane -R   # phải

# reload config
bind r source-file ~/.tmux.conf \; display "Reloaded!"

